#!/bin/bash -e


SCRIPT_DIR=$(dirname "$0")
TMP_DIR="$SCRIPT_DIR/../tmp"

source "$SCRIPT_DIR/helpers"

TARGET_REPO="https://github.com/golang/tools.git"
VERSION="v$(cat "$SCRIPT_DIR"/../version)"


print_usage(){
    echo "Usage: scripts/test --version=vXX --target=XXXXX"
    echo "--version   : docker image version to test - Default: latest"
    echo "--target    : git repository to target     - Default: https://github.com/golang/tools.git"
    echo "--signature : signature file to use         - Default: test/sample_rules.yml"
    echo "--help      : show help"
}

while [ $# -gt 0 ]; do

  case "$1" in
  --help)
      print_usage
      exit 0
      ;;

      --version=*)
      VERSION="${1#*=}"
      ;;

      --target=*)
      TARGET_REPO="${1#*=}"
      ;;

      *)
      echo "***************************"
      echo "* Error: Invalid argument.*"
      echo "***************************"
      print_usage
      exit 1
  esac
  shift

done

echo "Using version $VERSION"
echo "Using target  $TARGET_REPO"


mkdir -p "$TMP_DIR"

echo "Cloning target in $TMP_DIR"
cloneRepo "$TMP_DIR" "$TARGET_REPO"
TARGET_REPO=$(pwd)/target-repo

echo "Running scan.."
docker run -v "$(pwd)":/tmp michaelgrifalconi/tg:"$VERSION" -signatures="/tmp/test/sample_rules.yml" -repo="/tmp/tmp/target-repo"
